Compute unordered TED
s-match/s-match-spsm pull request #3
Opened 2016-12-01 11:01 UTC by DavidLeoni

Fix by @gbella: Modified the tree edit distance algorithm to compute *unordered* TED

The previous SPSM version implemented an ordered tree edit distance algorithm which did not consider the two trees A(B,C) and A(C,B) as identical (where B and C are siblings and children of A). As the most typical use case of SPSM is matching of function signatures, unordered TED (where the order of the arguments does not make a difference) is a more suitable solution. The new SPSM version thus implements unordered TED. Note that, while unordered TED in its generality is NP-complete, the implementation within SPSM is still polynomial because of preexisting simplifications in the underlying TED algorithm (substitution operations can only be done on the same level, deletion and insertion are only possible on leaves).

2016-12-01 19:25 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/filters/SPSMMappingFilter.java
> +     * @param mapping          the original SMATCH mappings
SMATCH -> S-Match.

2016-12-01 19:26 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/filters/SPSMMappingFilter.java
> +    protected Map<INode,INode> copyTree(INode from, INode to) {
space after ,

2016-12-01 19:26 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/filters/SPSMMappingFilter.java
> +        Map<INode,INode> copyMap = new HashMap<>();
space after ,

2016-12-01 19:29 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/filters/SPSMMappingFilter.java
> +     * @param rscList          List of source siblings to be reordered.
Having two names with 1-letter difference makes confusing them very easy. And often leads to hard to find bugs due to typos. Moreover, half of the name is "List" which is type and is mostly irrelevant in any modern IDE. Worth renaming.

2016-12-01 19:30 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/filters/SPSMMappingFilter.java
> +
extra line

2016-12-01 19:31 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/filters/SPSMMappingFilter.java
> +     * @param rscList     source list of reordered siblings
same problem with names as above

2016-12-01 19:33 UTC, autayeu requested changes
See notes. Also, it would be nice to increase test coverage when adding new behavior.

2016-12-02 09:46 UTC, DavidLeoni commented
I pushed the requested formatting. For the tests, well I'm all for testing but now we need to release. 
@gbella : Maybe it would make sense in the future to schedule another maintenance release that just adds at least high-level tests to all components.

2016-12-02 21:17 UTC, merged